{% set name = "clr_loader" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8b67503b44b6e36643edeb3c5b582e64bc63db33682e10dbd4d03397b7c835b
  patches:
    - dotnet-build-output.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - dotnet-sdk >=5
  host:
    - python >=3.0
    - pip
    - setuptools
    - wheel
  run:
    - cffi >=1.13
    - python >=3.0

test:
  imports:
    - clr_loader
  requires:
    - pip
    - dotnet-runtime 6.0
    - importlib_resources
    - mono
  commands:
    - pip check

about:
  home: https://github.com/pythonnet/clr-loader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generic pure Python loader for .NET runtimes
  dev_url: https://github.com/pythonnet/clr-loader

extra:
  recipe-maintainers:
    - m-rossi
