{% set name = "clr_loader" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6af3d582c3de55ce9e9e676d2b3dbf6bc680c4ea8f76c58786739a5bdcf6b52d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - dotnet-sdk >=6
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=75
    - setuptools-scm
    - wheel
  run:
    - cffi >=1.17
    - python >={{ python_min }}

test:
  imports:
    - clr_loader
  requires:
    - pip
    - python {{ python_min }}
    - dotnet-runtime 6.0
    - importlib_resources
    - mono
  commands:
    - pip check

about:
  home: https://github.com/pythonnet/clr-loader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generic pure Python loader for .NET runtimes
  dev_url: https://github.com/pythonnet/clr-loader

extra:
  recipe-maintainers:
    - m-rossi
